language: CSharp
mono:
 - latest
install:
 - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version 1.0.0-preview1-002702 --install-dir ~/dotnet
 - sudo ln -s ~/dotnet/dotnet /usr/local/bin
 - cd src/Pokecalc
 - dotnet restore
script:
 - dotnet build
 - cd ../Pokecalc.Test
 - dotnet test
